import type { Metadata } from "next"
import { Open_Sans } from "next/font/google"
import "./globals.css"
import Header from "@/components/shell/header"
import Footer from "@/components/shell/footer"
import { cn } from "@/lib/utils"

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(openSans.className, "antialiased")}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
